# Generated by Django 5.2.17 on 2026-10-01 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('clinic', '0004_alter_prescriptiondrug_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='primary_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='clinic.department'),
        ),
    ]
