# Generated by Django 5.2.17 on 2026-09-11 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kr', models.CharField(max_length=50)),
                ('name_local', models.CharField(blank=True, max_length=100)),
                ('sex', models.CharField(choices=[('M', '남'), ('F', '여')], max_length=1)),
                ('birth_year', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('reg_no', models.PositiveIntegerField()),
                ('weight', models.FloatField(blank=True, null=True)),
                ('bp', models.CharField(blank=True, max_length=20)),
                ('pr', models.PositiveIntegerField(blank=True, null=True)),
                ('bt', models.FloatField(blank=True, null=True)),
                ('bst', models.FloatField(blank=True, null=True)),
                ('is_preg', models.BooleanField(default=False)),
                ('has_htn', models.BooleanField(default=False)),
                ('has_dm', models.BooleanField(default=False)),
                ('has_tbc', models.BooleanField(default=False)),
                ('has_hepatitis', models.BooleanField(default=False)),
                ('has_allergy', models.BooleanField(default=False)),
                ('allergy_detail', models.CharField(blank=True, max_length=200)),
                ('has_operation', models.BooleanField(default=False)),
                ('operation_detail', models.CharField(blank=True, max_length=200)),
                ('history_etc', models.CharField(blank=True, max_length=200)),
                ('chief_complaint', models.CharField(blank=True, max_length=200)),
                ('symptom_duration', models.CharField(blank=True, max_length=100)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='clinic.mission')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='clinic.patient')),
            ],
            options={
                'unique_together': {('mission', 'visit_date', 'reg_no')},
            },
        ),
        migrations.CreateModel(
            name='VisitDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_done', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_visits', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_departments', to='clinic.visit')),
            ],
        ),
    ]
