# Generated by Django 5.2.17 on 2026-09-12 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_patient_visit_visitdepartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ingredient', models.CharField(blank=True, max_length=200)),
                ('usage', models.CharField(blank=True, max_length=200)),
                ('cat1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drugs', to='clinic.drugcategory1')),
                ('cat2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drugs', to='clinic.drugcategory2')),
            ],
        ),
        migrations.CreateModel(
            name='DrugBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('donation', '후원'), ('local', '현지'), ('purchase', '구매'), ('local_purchase', '현지구매'), ('etc', '기타')], max_length=20)),
                ('source_detail', models.CharField(blank=True, max_length=100)),
                ('received_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('unit_qty', models.PositiveIntegerField()),
                ('unit_label', models.CharField(max_length=20)),
                ('total_qty', models.PositiveIntegerField()),
                ('remaining_qty', models.PositiveIntegerField()),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='clinic.drug')),
            ],
        ),
        migrations.CreateModel(
            name='MissionStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_qty', models.PositiveIntegerField()),
                ('remaining_qty', models.PositiveIntegerField()),
                ('donated_qty', models.PositiveIntegerField(default=0)),
                ('is_settled', models.BooleanField(default=False)),
                ('drugbatch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mission_stocks', to='clinic.drugbatch')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_stocks', to='clinic.mission')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinical_note', models.TextField(blank=True)),
                ('is_dispensed', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='clinic.department')),
                ('visit_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='clinic.visitdepartment')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose_per_intake', models.FloatField(blank=True, null=True)),
                ('frequency_per_day', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescription_items', to='clinic.drug')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clinic.prescription')),
            ],
        ),
    ]
