# Generated by Django 5.2.17 on 2026-09-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_drug_drugbatch_missionstock_prescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptiondrug',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
